name: "CI: Visualizer Image Cleanup"

"on":
  # Weekly on Thursday at 03:41 UTC
  schedule:
    - cron: "41 3 * * 4"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  ghcr-cleanup:
    name: GHCR cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup old images
        uses: ghcr-manager/ghcr-cleanup-manager@4f9383ec3f79750a9085b05eea317c666bda183e # v1.1.8
        with:
          command: cleanup
          token: ${{ github.token }}
          owner: ${{ github.repository_owner }}
          package: ${{ github.event.repository.name }}-visualizer
          upload-artifacts: true
          use-regex: true
          # delete-tags: '^(?!(latest|v[0-9]+|v[0-9]+\.[0-9]+\.[0-9]+)$).+'
          exclude-tags: |
            ^latest$
            ^v[0-9]+$
            ^v[0-9]+\.[0-9]+\.[0-9]+$
          keep-n-tagged: 1
          delete-untagged: true
          scan-after-cleanup: "true"
